server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri:
        native:
          search-locations: file:///D:/workspace-mine/spring-cloud-demo/configs
  profiles:
    active: native